[package]
name = "biller"
version = "1.0.0"
edition = "2024"

[dependencies]
image = "0.25.10"
ocr-rs = "2.2.2"
regex = "1.12.3"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [ "postgres", "runtime-tokio-native-tls", "rust_decimal"] }
dotenvy = "0.15"
async-trait = "0.1"
rust_decimal = "1.34"
futures = "0.3"
chrono = "0.4"
